### ISSUE TITLE
Speech recognition compatability

### ISSUE THREAD

**Issue by IchigoKurosakii** [pbloem/language-models#2]
I am trying to add a Language model to an end to end speech recognition system and I want to add it to a trained RNNLM. If I trained the words model how can I combine it to the speech recognition system

I am using networks similar to this 
https://github.com/simoninithomas/DNN-Speech-Recognizer

**Comment by pbloem** [comment]
In that case, you probably want to build the model from scratch. You can take some inspiration from the models in this repository, but you'll get a lot more out of reading the relevant literature. 

This blog post might provide a good starting point: https://blog.keras.io/a-ten-minute-introduction-to-sequence-to-sequence-learning-in-keras.html
